<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Assignments</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>








<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Sara's Site</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Assignments.html">Assignments</a>
</li>
<li>
  <a href="Links.html">Links</a>
</li>
<li>
  <a href="Exam-1.html">Exams</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Assignments</h1>

</div>


<p>This page will contain all the assignments you submit for the class.</p>
<div id="instructions-for-all-assignments" class="section level3">
<h3>Instructions for all assignments</h3>
<p>I want you to submit your assignment as a PDF, so I can keep a record of what the code looked like that day. I also want you to include your answers on your personal GitHub website. This will be good practice for editing your website and it will help you produce something you can keep after the class is over.</p>
<ol style="list-style-type: decimal">
<li><p>Download the Assignment1.Rmd file from Canvas. You can use this as a template for writing your answers. It’s the same as what you can see on my website in the Assignments tab. Once we’re done with this I’ll edit the text on the website to include the solutions.</p></li>
<li><p>On RStudio, open a new R script in RStudio (File &gt; New File &gt; R Script). This is where you can test out your R code. You’ll write your R commands and draw plots here.</p></li>
<li><p>Once you have finalized your code, copy and paste your results into this template (Assignment 1.Rmd). For example, if you produced a plot as the solution to one of the problems, you can copy and paste the R code in R markdown by using the <code>``{r} ```</code> command. Answer the questions in full sentences and Save.</p></li>
<li><p>Produce a PDF file with your answers. To do this, knit to PDF (use Knit button at the top of RStudio), locate the PDF file in your docs folder (it’s in the same folder as the Rproj), and submit that on on Canvas in Assignment 1.</p></li>
<li><p>Build Website, go to GitHub desktop, commit and push. Now your solutions should be on your website as well.</p></li>
</ol>
</div>
<div id="assignment-1" class="section level1">
<h1>Assignment 1</h1>
<p><strong>Collaborators: Rachael Villari, Michaela Reiser. </strong></p>
<p>This assignment is due on Canvas on Monday 9/20 before class, at 10:15 am. Include the name of anyone with whom you collaborated at the top of the assignment.</p>
<p>Collaborators: Rachael Villari, Michaela Reiser</p>
<div id="problem-1" class="section level3">
<h3>Problem 1</h3>
<p>Install the datasets package on the console below using <code>install.packages("datasets")</code>. Now load the library.</p>
<pre class="r"><code>library(datasets)</code></pre>
<p>Load the USArrests data set and rename it <code>dat</code>. Note that this dataset comes with R, in the package datasets, so there’s no need to load data from your computer. Why is it useful to rename the dataset?</p>
<p>Answer: It is useful to rename the dataset so we have a single, shorter variable to account for the whole dataset</p>
<pre class="r"><code>dat &lt;- USArrests</code></pre>
</div>
<div id="problem-2" class="section level3">
<h3>Problem 2</h3>
<p>Use this command to make the state names into a new variable called State.</p>
<pre class="r"><code>dat$state &lt;- tolower(rownames(USArrests))</code></pre>
<p>This dataset has the state names as row names, so we just want to make them into a new variable. We also make them all lower case, because that will help us draw a map later - the map function requires the states to be lower case.</p>
<p>List the variables contained in the dataset <code>USArrests</code>.</p>
<p>Answer: Murder, Assault, Urban Population, Rape</p>
<pre class="r"><code>names(dat)</code></pre>
<pre><code>## [1] &quot;Murder&quot;   &quot;Assault&quot;  &quot;UrbanPop&quot; &quot;Rape&quot;</code></pre>
</div>
<div id="problem-3" class="section level3">
<h3>Problem 3</h3>
<p>What type of variable (from the DVB chapter) is <code>Murder</code>?</p>
<p>Answer: quantitative</p>
<p>What R Type of variable is it?</p>
<p>Answer: numeric</p>
</div>
<div id="problem-4" class="section level3">
<h3>Problem 4</h3>
<p>What information is contained in this dataset, in general? What do the numbers mean?</p>
<p>Answer: The numbers are the frequency of arrests per crime in each state and the urban population is the percentage of people in each state who live in an urban area. The information in general is the US Arrests of each crime in each state.</p>
</div>
<div id="problem-5" class="section level3">
<h3>Problem 5</h3>
<p>Draw a histogram of <code>Murder</code> with proper labels and title.</p>
<pre class="r"><code>hist(dat$Murder, main = &quot;Histogram of US Arrests
     of Murder&quot;, xlab = &quot;US Arrests of Murder&quot;, 
     xlim = c(0,20), ylim = c(0, 15))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="problem-6" class="section level3">
<h3>Problem 6</h3>
<p>Please summarize <code>Murder</code> quantitatively. What are its mean and median? What is the difference between mean and median? What is a quartile, and why do you think R gives you the 1st Qu. and 3rd Qu.?</p>
<p>Answer: Min: 0.8 Max:17.4 Mean:7.788 Median:7.250 Q1: 4.075 Q3: 11.250 The difference between mean and median is that the mean gives the average of all murders while the median relates to the value at the midpoint of the data set. R gives the 1st and 3rd quartiles so we can have a fuller picture of our dataset and we can have a better idea of where our median falls.</p>
<pre class="r"><code>summary(dat$Murder)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.800   4.075   7.250   7.788  11.250  17.400</code></pre>
</div>
<div id="problem-7" class="section level3">
<h3>Problem 7</h3>
<p>Repeat the same steps you followed for <code>Murder</code>, for the variables <code>Assault</code> and <code>Rape</code>. Now plot all three histograms together. You can do this by using the command <code>par(mfrow=c(3,1))</code> and then plotting each of the three.</p>
<pre class="r"><code>hist(dat$Assault, main = &quot;Histogram of US Arrests of Assault&quot;,
     xlab = &quot;US Arrests of Assault&quot;,xlim = c(0,350), 
     ylim = c(0,15))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-7-1.png" width="480" /></p>
<pre class="r"><code>hist(dat$UrbanPop, main = &quot;Histogram of US Urban Population&quot;,
     xlab = &quot;US Urban Population&quot;, xlim = c(0,100), 
     ylim = c(0,15))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-7-2.png" width="480" /></p>
<pre class="r"><code>hist(dat$Rape, main = &quot;Histogram of US Arrests of Rape&quot;, 
     xlab = &quot;US Arrests of Rape&quot;, xlim = c(0,50), 
     ylim = c(0,15))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-7-3.png" width="480" /></p>
<pre class="r"><code>par(mfrow=c(3,1))
hist(dat$Assault, main = &quot;Histogram of US Arrests of Assault&quot;, 
     xlab = &quot;US Arrests of Assault&quot;, xlim = c(0,350), 
     ylim = c(0,15))
hist(dat$UrbanPop, main = &quot;Histogram of US Urban Population&quot;,
     xlab = &quot;US Urban Population&quot;, xlim = c(0,100), 
     ylim = c(0,15))
hist(dat$Rape, main = &quot;Histogram of US Arrests of Rape&quot;, 
     xlab = &quot;US Arrests of Rape&quot;, xlim = c(0,50), 
     ylim = c(0,15))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-7-4.png" width="480" /></p>
<p>What does the command par do, in your own words (you can look this up by asking R <code>?par</code>)?</p>
<p>Answer: command par allows one to see all three graphs together in order to compare them more easily</p>
<p>What can you learn from plotting the histograms together?</p>
<p>Answer: You can learn the distributions against each other and see which variable has the most uniform or skewed distribution.</p>
</div>
<div id="problem-8" class="section level3">
<h3>Problem 8</h3>
<p>In the console below (not in text), type <code>install.packages("maps")</code> and press Enter, and then type <code>install.packages("ggplot2")</code> and press Enter. This will install the packages so you can load the libraries.</p>
<p>Run this code:</p>
<pre class="r"><code>install.packages(&quot;maps&quot;)
install.packages(&quot;ggplot2&quot;)
library(&#39;maps&#39;) 
library(&#39;ggplot2&#39;) 

ggplot(dat, aes(map_id=state, fill=Murder)) + 
  geom_map(map=map_data(&quot;state&quot;)) + 
  expand_limits(x=map_data(&quot;state&quot;)$long, y=map_data(&quot;state&quot;)$lat)</code></pre>
<p>What does this code do? Explain what each line is doing.</p>
<p>Answer: The first two lines of code are installing the packages onto R so we can use the functions located within the package. Calling the library of maps and ggplot2 allows us to access these two functions within our own R Script. Lines 167-169 are plotting our USArrests data located in the variable dat, specifically the variable of “Murder.” It maps the data by U.S state of the different concentrations of murder arrests.</p>
<p><span class="math display">\[\\[2in]\]</span></p>
</div>
</div>
<div id="assignment-2" class="section level1">
<h1>Assignment 2</h1>
<p>###Problem 1: Load Data</p>
<pre class="r"><code>dat.nsduh &lt;- read.csv(&quot;dat.nsduh.small.1.csv&quot;)</code></pre>
<p>What are the dimensions of the datset?</p>
<pre class="r"><code>dim(dat.nsduh)</code></pre>
<pre><code>## [1] 171   7</code></pre>
<p>Answer: 171 rows and 7 columns</p>
<p>###Problem 2: Variables</p>
<p>Describe the variables in the dataset</p>
<p>Answer: Answer: Variable names are “mjage,” “cigage,” “iralcage,” age2," “sexatract,” “speakengl,” and “irsex.” mj, alc, and age are quantitative variables while the others are categorical coded as an integer. mjage = the age that the individual first used marijuana, cigeage = the age that the individual first had a cigarette, iralcage = age to first drink alcohol, age2 = recoded age, sexatract = sexual attraction, speakengl = how well does one speak english, irsex = gender</p>
<pre class="r"><code>names(dat.nsduh)</code></pre>
<pre><code>## [1] &quot;mjage&quot;     &quot;cigage&quot;    &quot;iralcage&quot;  &quot;age2&quot;      &quot;sexatract&quot; &quot;speakengl&quot;
## [7] &quot;irsex&quot;</code></pre>
<pre class="r"><code>summary(dat.nsduh)</code></pre>
<pre><code>##      mjage           cigage         iralcage          age2      
##  Min.   : 7.00   Min.   :10.00   Min.   : 5.00   Min.   : 4.00  
##  1st Qu.:14.00   1st Qu.:15.00   1st Qu.:13.00   1st Qu.:13.00  
##  Median :16.00   Median :17.00   Median :15.00   Median :15.00  
##  Mean   :15.99   Mean   :17.65   Mean   :14.95   Mean   :13.98  
##  3rd Qu.:17.50   3rd Qu.:19.00   3rd Qu.:17.00   3rd Qu.:15.00  
##  Max.   :35.00   Max.   :50.00   Max.   :23.00   Max.   :17.00  
##    sexatract       speakengl        irsex      
##  Min.   : 1.00   Min.   :1.00   Min.   :1.000  
##  1st Qu.: 1.00   1st Qu.:1.00   1st Qu.:1.000  
##  Median : 1.00   Median :1.00   Median :1.000  
##  Mean   : 3.07   Mean   :1.07   Mean   :1.468  
##  3rd Qu.: 1.00   3rd Qu.:1.00   3rd Qu.:2.000  
##  Max.   :99.00   Max.   :3.00   Max.   :2.000</code></pre>
<p>What is this dataset about? Who collected the data, what kind of sample is it, and what was the purpose of generating the data?</p>
<p>Answer: This is data from the National Survey on Drug Use and Health, about the drug use, alcohol use, cigarette use, and demographics of a random sample taken from all 50 states</p>
<p>the purpose of generating the data is to track levels of substance use and identify the groups that are the main users</p>
<p>###Problem 3: Age and gender</p>
<p>What is the age distribution of the sample like? Make sure you read the codebook to know what the variable values mean.</p>
<pre class="r"><code>hist(dat.nsduh$age2)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>summary(dat.nsduh$age2)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    4.00   13.00   15.00   13.98   15.00   17.00</code></pre>
<p>Answer: the age distribution has a left skew. The mean is 13.98, median is 15, First quartile is 13 and the third quartile is 15 with a min of 4 and max of 17. This means that the average age of the sample is between 26 and 29 years old, the minimum is around 15 years of age, and the max is around 65+ years</p>
<p>Do you think this age distribution representative of the US population? Why or why not?</p>
<p>Answer:No I do not think this age distribution is representative of the U.S population because the distribution is skewed, a true representation would be closer to a uniform distribution</p>
<p>Is the sample balanced in terms of gender? If not, are there more females or males?</p>
<pre class="r"><code>hist(dat.nsduh$irsex)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>Answer: the sample contains slightly more males than females</p>
<p>Use this code to draw a stacked bar plot to view the relationship between sex and age. What can you conclude from this plot?</p>
<pre class="r"><code>tab.agesex &lt;- table(dat.nsduh$irsex, dat.nsduh$age2)
barplot(tab.agesex,
        main = &quot;Stacked barchart&quot;,
        xlab = &quot;Age category&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.agesex),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Answer: One can conclude that the majority of individuals lie within the 13-15 age category. The younger age categories are mainly male dominated. This is a left skewed distribution where most of the data is in the higher age categories</p>
<p>###Problem 4: Substance use</p>
<pre class="r"><code>par(mfrow=c(3,1))
hist(dat.nsduh$cigage, main = &quot;Age of First Cigarette&quot;,xlab = &quot;Age&quot;)
hist(dat.nsduh$mjage, main = &quot;Age of First Marijuana Use&quot;, xlab = &quot;Age&quot;)
hist(dat.nsduh$iralcage, main = &quot;Age of First Drink&quot;, xlab = &quot;Age&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-15-1.png" width="672" /> For which of the three substances included in the dataset (marijuana, alcohol, and cigarettes) do individuals tend to use the substance earlier?</p>
<p>Answer: Alcohol is the substance that individuals tend to use earlier</p>
<p>###Problem 5: Sexual attraction</p>
<p>What does the distribution of sexual attraction look like? Is this what you expected?</p>
<pre class="r"><code>dat.nsduh$sexatract[dat.nsduh$sexatract == 99] &lt;- NA
hist(dat.nsduh$sexatract, main = &quot;Sexual Attraction&quot;, xlab = &quot;Sexual Attraction&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Answer: yes this is what one would expect because the majority of the U.S Population is heterosexual</p>
<p>What is the distribution of sexual attraction by gender?</p>
<pre class="r"><code>par(mar=c(1,1,1,1))

tab.gendersexatract &lt;- table(dat.nsduh$irsex, dat.nsduh$sexatract)
barplot(tab.gendersexatract,
        main = &quot;Relationship of Sexual Attraction and Gender&quot;,
        xlab = &quot;Sexual Attraction&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.gendersexatract),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>Answer: The stacked bar plot shows a right skew where the majority of individuals are purely heterosexual. The majority of men self report as heterosexual while there is marginally more balance in women between hetersexuality and being mostly attracted to the opposite gender (2).</p>
<p>###Problem 6: English speaking</p>
<p>What does the distribution of English speaking look like in the sample? Is this what you might expect for a random sample of the US population?</p>
<pre class="r"><code>hist(dat.nsduh$speakengl, main = &quot;English Speaking&quot;, xlab = &quot;English Speaking&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
<p>Answer: The majority of individuals can speak English very well while the minority report speaking it well or not well. This is representative of the U.S</p>
<p>Are there more English speaker females or males?</p>
<pre class="r"><code>tab.genderspeakengl &lt;- table(dat.nsduh$irsex, dat.nsduh$speakengl)
barplot(tab.genderspeakengl,
        main = &quot;Relationship of Gender and English Fluency&quot;,
        xlab = &quot;English fluency&quot;, ylab = &quot;Frequency&quot;,
        legend.text = rownames(tab.genderspeakengl),
        beside = FALSE) # Stacked bars (default)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>Answer: there are more English speaking males</p>
</div>
<div id="assignment-3" class="section level1">
<h1>Assignment 3</h1>
<hr />
<p><strong>Collaborators: </strong>.</p>
<p>This assignment is due on Canvas on Wednesday 10/27/2021 before class, at 10:15 am. Include the name of anyone with whom you collaborated at the top of the assignment.</p>
<p>Submit your responses as either an HTML file or a PDF file on Canvas. Also, please upload it to your website.</p>
<p>Save the file (found on Canvas) crime_simple.txt to the same folder as this file (your Rmd file for Assignment 3).</p>
<p>Load the data.</p>
<pre class="r"><code>library(readr)
library(knitr)
dat.crime &lt;- read_delim(&quot;crime_simple.txt&quot;, delim = &quot;\t&quot;)</code></pre>
<p>This is a dataset from a textbook by Brian S. Everitt about crime in the US in 1960. The data originate from the Uniform Crime Report of the FBI and other government sources. The data for 47 states of the USA are given.</p>
<p>Here is the codebook:</p>
<p>R: Crime rate: # of offenses reported to police per million population</p>
<p>Age: The number of males of age 14-24 per 1000 population</p>
<p>S: Indicator variable for Southern states (0 = No, 1 = Yes)</p>
<p>Ed: Mean of years of schooling x 10 for persons of age 25 or older</p>
<p>Ex0: 1960 per capita expenditure on police by state and local government</p>
<p>Ex1: 1959 per capita expenditure on police by state and local government</p>
<p>LF: Labor force participation rate per 1000 civilian urban males age 14-24</p>
<p>M: The number of males per 1000 females</p>
<p>N: State population size in hundred thousands</p>
<p>NW: The number of non-whites per 1000 population</p>
<p>U1: Unemployment rate of urban males per 1000 of age 14-24</p>
<p>U2: Unemployment rate of urban males per 1000 of age 35-39</p>
<p>W: Median value of transferable goods and assets or family income in tens of $</p>
<p>X: The number of families per 1000 earning below 1/2 the median income</p>
<p>We are interested in checking whether the reported crime rate (# of offenses reported to police per million population) and the average education (mean number of years of schooling for persons of age 25 or older) are related.</p>
<ol style="list-style-type: decimal">
<li>How many observations are there in the dataset? To what does each observation correspond?</li>
</ol>
<pre class="r"><code>names(dat.crime)</code></pre>
<pre><code>##  [1] &quot;R&quot;   &quot;Age&quot; &quot;S&quot;   &quot;Ed&quot;  &quot;Ex0&quot; &quot;Ex1&quot; &quot;LF&quot;  &quot;M&quot;   &quot;N&quot;   &quot;NW&quot;  &quot;U1&quot;  &quot;U2&quot; 
## [13] &quot;W&quot;   &quot;X&quot;</code></pre>
<p><strong>R corresponds to the crime rate. Age corresponds to the number of males of age 14-24 per 1000 population.S is the ndicator variable for Southern states where 0 = No and 1 = Yes. Ed is the mean of years of schooling x 10 for persons of age 25 or older. Ex0 is the 1960 per capita expenditure on police by state and local government. Ex1 is the 1959 per capita expenditure on police by state and local government. LF is the labor force participation rate per 1000 civilian urban males age 14-24. M is the number of males per 1000 females. N is the state population size in hundred thousands.NW is the number of non-whites per 1000 population.U1 is the unemployment rate of urban males per 1000 of age 14-24. U2 is the unemployment rate of urban males per 1000 of age 35-39. W is the median value of transferable goods and assets or family income in tens of $. Finally, X is the number of families per 1000 earning below 1/2 the median income</strong></p>
<ol start="2" style="list-style-type: decimal">
<li>Draw a scatterplot of the two variables. Calculate the correlation between the two variables. Can you come up with an explanation for this relationship?</li>
</ol>
<pre class="r"><code>plot(dat.crime$Ed, dat.crime$R, main = &quot;Relationship between
     Education Level and Crime Reporting&quot;, ylab = &quot;# of offenses
     reported per mil&quot;, xlab = &quot;Mean of years of schooling x 10
     for persons of age 25 or older&quot;,xlim = c(80, 130), ylim 
     = c(0, 200))</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-22-1.png" width="576" /></p>
<pre class="r"><code>cor(dat.crime$Ed, dat.crime$R)</code></pre>
<pre><code>## [1] 0.3228349</code></pre>
<p><strong>There is a correlation of 0.32 between Education level and Crime reporting. This suggests that there is a positive relationship between the two variables. This could be because as one becomes more educated, one becomes more aware of what is illegal and wants to work toward crime reduction and making their surroudning space safer.</strong></p>
<ol start="3" style="list-style-type: decimal">
<li>Regress reported crime rate (y) on average education (x) and call this linear model crime.lm and write the summary of the regression by using this code, which makes it look a little nicer</li>
</ol>
<pre class="r"><code># Remember to remove eval=FALSE above!
dat.crime$Ed.c = scale(dat.crime$Ed, center=TRUE, scale=FALSE)
crime.lm &lt;- lm(formula = R ~ Ed, data = dat.crime)
summary(crime.lm)</code></pre>
<pre><code>## 
## Call:
## lm(formula = R ~ Ed, data = dat.crime)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -60.061 -27.125  -4.654  17.133  91.646 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)  
## (Intercept) -27.3967    51.8104  -0.529   0.5996  
## Ed            1.1161     0.4878   2.288   0.0269 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 37.01 on 45 degrees of freedom
## Multiple R-squared:  0.1042, Adjusted R-squared:  0.08432 
## F-statistic: 5.236 on 1 and 45 DF,  p-value: 0.02688</code></pre>
<pre class="r"><code>kable(summary(crime.lm)$coef, digits = 2)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">Estimate</th>
<th align="right">Std. Error</th>
<th align="right">t value</th>
<th align="right">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-27.40</td>
<td align="right">51.81</td>
<td align="right">-0.53</td>
<td align="right">0.60</td>
</tr>
<tr class="even">
<td align="left">Ed</td>
<td align="right">1.12</td>
<td align="right">0.49</td>
<td align="right">2.29</td>
<td align="right">0.03</td>
</tr>
</tbody>
</table>
<ol start="4" style="list-style-type: decimal">
<li>Are the four assumptions of linear regression satisfied? To answer this, draw the relevant plots. (Write a maximum of one sentence per assumption.)</li>
</ol>
<pre class="r"><code>plot(dat.crime$Ed.c, crime.lm$residuals, ylim=c(-100,100),
     main=&quot;Residuals vs. x&quot;, xlab=&quot;x, Scaled Crime Reporting
     Rate&quot;, ylab=&quot;Residuals&quot;)

abline(h = 0, lty=&quot;dashed&quot;)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
<pre class="r"><code>plot(crime.lm, which=1)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-24-2.png" width="672" /></p>
<pre class="r"><code>plot(crime.lm, which=2)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-24-3.png" width="672" /></p>
<p><strong>1. The Residuals versus Fitted plot shows no nonlinear trend as proved by the approximately flat red line fitting the linearity assumption. The independence assumption is met as shown by the residuals vs. x plot as there is no pattern of residuals shown. The homoscedasticity assumption is met as shown by the scatterplot in problem 2 as the points are random, but do not have any serious outliers. The normal population assumption is mostly met but could be argued that the right tail of the distribution is smaller than usual for a normal distribution. </strong></p>
<ol start="5" style="list-style-type: decimal">
<li>Is the relationship between reported crime and average education statistically significant? Report the estimated coefficient of the slope, the standard error, and the p-value. What does it mean for the relationship to be statistically significant?</li>
</ol>
<p><strong>Yes, the relationship between crime reporting and average education is statistically significant. The coefficient of the slope is 1.12, the standard error is 0.49, and the p-value is 0.03. The relationship being statistically significant is shown through the p-value being less than the alpha value of 0.05. It means that the results are not due to chance rather correlated to the relationship between the two studied variables.</strong></p>
<ol start="6" style="list-style-type: decimal">
<li>How are reported crime and average education related? In other words, for every unit increase in average education, how does reported crime rate change (per million) per state?</li>
</ol>
<p><strong>Reported crime and average education are related in that for every unit increase in education, reported crime rate increases by 1.12 units per million per state.</strong></p>
<ol start="7" style="list-style-type: decimal">
<li>Can you conclude that if individuals were to receive more education, then crime will be reported more often? Why or why not?</li>
</ol>
<p><strong>Yes, this can be concluded do to the statistical significance of education level and crime reporting in being compared to each other through linear regression. Along with the positive correlation of the scatterplot and all of the assumptions being met, there is a relationship between getting an education and being more likely to report crime.</strong></p>
</div>
<div id="assignment-4" class="section level1">
<h1>Assignment 4</h1>
<div id="loading-the-library-of-tidyverse-where-the-tidyverse-package-is-stored-to-access" class="section level4">
<h4>loading the library of tidyverse where the tidyverse package is stored to access</h4>
</div>
<div id="ggplot" class="section level4">
<h4>ggplot</h4>
<p>library(tidyverse) #### installing the package so one can reload it after every session</p>
<p>install.packages(“tidyverse”)</p>
</div>
<div id="calling-mpg-dataframe-a-data-frame-is-a-rectangular-collection-of-variables" class="section level4">
<h4>calling mpg dataframe A data frame is a rectangular collection of variables</h4>
</div>
<div id="in-the-columns-and-observations-in-the-rows.-mpg-contains-observations-collected" class="section level4">
<h4>(in the columns) and observations (in the rows). mpg contains observations collected</h4>
</div>
<div id="by-the-us-environmental-protection-agency-on-38-models-of-car." class="section level4">
<h4>by the US Environmental Protection Agency on 38 models of car.</h4>
<p>mpg</p>
<p>#&gt; # A tibble: 234 x 11 #&gt; manufacturer model displ year cyl trans drv cty hwy fl class #&gt; <chr> <chr> <dbl> <int> <int> <chr> <chr> <int> <int> <chr> <chr> #&gt; 1 audi a4 1.8 1999 4 auto(l5) f 18 29 p compa… #&gt; 2 audi a4 1.8 1999 4 manual(m5) f 21 29 p compa… #&gt; 3 audi a4 2 2008 4 manual(m6) f 20 31 p compa… #&gt; 4 audi a4 2 2008 4 auto(av) f 21 30 p compa… #&gt; 5 audi a4 2.8 1999 6 auto(l5) f 16 26 p compa… #&gt; 6 audi a4 2.8 1999 6 manual(m5) f 18 26 p compa… #&gt; # … with 228 more rows</p>
</div>
<div id="mapping-a-gg-scatterplot-that-maps-cars-engine-size-against-fuel-efficiency" class="section level4">
<h4>mapping a gg scatterplot that maps car’s engine size against fuel efficiency</h4>
</div>
<div id="shows-a-negative-relationship-between-x-and-y-variables" class="section level4">
<h4>shows a negative relationship between x and y variables</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))</p>
<p>#creating a reusable template for making graphs with ggplot2 ggplot(data = <DATA>) + <GEOM_FUNCTION>(mapping = aes(<MAPPINGS>))</p>
</div>
<div id="mapping-aesthetics-in-your-plot-to-the-variables-in-the-dataset-maps-class-to" class="section level4">
<h4>mapping aesthetics in your plot to the variables in the dataset, maps class to</h4>
</div>
<div id="color-aesthetic" class="section level4">
<h4>color aesthetic</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = class))</p>
</div>
<div id="mapping-class-against-size-aesthetic" class="section level4">
<h4>mapping class against size aesthetic</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, size = class)) #### &gt; Warning: Using size for a discrete variable is not advised.</p>
</div>
<div id="mapping-class-to-the-alpha-aesthetic-which-controls-the-transparency-of-the-points" class="section level4">
<h4>mapping class to the alpha aesthetic, which controls the transparency of the points,</h4>
</div>
<div id="or-to-the-shape-aesthetic-which-controls-the-shape-of-the-points" class="section level4">
<h4>or to the shape aesthetic, which controls the shape of the points</h4>
</div>
<div id="left" class="section level4">
<h4>Left</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, alpha = class))</p>
</div>
<div id="right" class="section level4">
<h4>Right</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, shape = class))</p>
</div>
<div id="setting-aesthetic-properties-of-geom-manually-making-all-of-the-points-blue" class="section level4">
<h4>setting aesthetic properties of geom manually, making all of the points blue</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy), color = “blue”)</p>
</div>
<div id="missed-parentheses-so-the-point-do-not-come-out-blue" class="section level4">
<h4>missed parentheses so the point do not come out blue</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy, color = “blue”))</p>
</div>
<div id="plus-sign-must-come-at-the-end-of-the-line-not-the-beginning" class="section level4">
<h4>plus sign must come at the end of the line not the beginning</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))</p>
</div>
<div id="facetting-plot-by-a-single-variable.-first-argument-is-a-formula-followed-by" class="section level4">
<h4>facetting plot by a single variable. First argument is a formula, followed by ~</h4>
</div>
<div id="followed-by-variable-name-where-formula-is-the-name-of-a-data-structure-in-r-the-variable-that" class="section level4">
<h4>followed by variable name where formula is the name of a data structure in R/ The variable that</h4>
</div>
<div id="is-passed-to-facet_wrap-should-be-discrete" class="section level4">
<h4>is passed to facet_wrap should be discrete</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ class, nrow = 2)</p>
</div>
<div id="facetting-your-plot-on-the-combination-of-two-variables-add-facet_grid-to-your" class="section level4">
<h4>Facetting your plot on the combination of two variables, add facet_grid() to your</h4>
</div>
<div id="plot-call.-the-first-argument-of-facet_grid-is-also-a-formula.-this-time-the" class="section level4">
<h4>plot call. The first argument of facet_grid() is also a formula. This time the</h4>
</div>
<div id="formula-should-contain-two-variable-names-separated-by-a-.-the-empty-grids" class="section level4">
<h4>formula should contain two variable names separated by a ~. The empty grids</h4>
</div>
<div id="show-that-there-is-no-data-attributed-to-this-specific-variable" class="section level4">
<h4>show that there is no data attributed to this specific variable</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ cyl)</p>
</div>
<div id="code-creates-4-facet-columns-that-are-generated-by-the-.-the-data-maps" class="section level4">
<h4>Code creates 4 facet columns that are generated by the “.” The data maps</h4>
</div>
<div id="engine-size-against-fuel-efficiency" class="section level4">
<h4>engine size against fuel efficiency</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(drv ~ .)</p>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_grid(. ~ cyl)</p>
</div>
<div id="facets-columns-and-rows-of-each-type-of-car-variable-engine-size-against-fuel" class="section level4">
<h4>facets columns and rows of each type of car variable, engine size against fuel</h4>
</div>
<div id="efficiency" class="section level4">
<h4>efficiency</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + facet_wrap(~ class, nrow = 2)</p>
</div>
<div id="point-geom-representation-of-the-data" class="section level4">
<h4>point geom representation of the data</h4>
</div>
<div id="left-1" class="section level4">
<h4>left</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy))</p>
</div>
<div id="right-smooth-geom-representation-of-the-data" class="section level4">
<h4>right smooth geom representation of the data</h4>
<p>ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))</p>
</div>
<div id="drawing-a-different-line-with-a-different-linetype-for-each-unique-value-of" class="section level4">
<h4>drawing a different line, with a different linetype, for each unique value of</h4>
</div>
<div id="the-variable-that-you-map-to-linetype." class="section level4">
<h4>the variable that you map to linetype.</h4>
<p>ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))</p>
</div>
<div id="geom-smooth-uses-a-single-geometric-object-to-display-multiple-rows-of-data." class="section level4">
<h4>geom smooth uses a single geometric object to display multiple rows of data.</h4>
</div>
<div id="setting-the-group-aesthetic-to-a-categorical-variable-to-draw-multiple-objects." class="section level4">
<h4>Setting the group aesthetic to a categorical variable to draw multiple objects.</h4>
</div>
<div id="ggplot2-draws-a-separate-object-for-each-unique-value-of-the-grouping-variable." class="section level4">
<h4>ggplot2 draws a separate object for each unique value of the grouping variable.</h4>
</div>
<div id="in-practice-ggplot2-will-automatically-group-the-data-for-these-geoms-whenever-you" class="section level4">
<h4>In practice, ggplot2 will automatically group the data for these geoms whenever you</h4>
</div>
<div id="map-an-aesthetic-to-a-discrete-variable-linetype-example" class="section level4">
<h4>map an aesthetic to a discrete variable (linetype example)</h4>
<p>ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy))</p>
<p>ggplot(data = mpg) + geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))</p>
<p>ggplot(data = mpg) + geom_smooth( mapping = aes(x = displ, y = hwy, color = drv), show.legend = FALSE )</p>
</div>
<div id="displaying-multiple-geoms-in-the-same-plot-by-adding-multiple-geom-functions-to" class="section level4">
<h4>displaying multiple geoms in the same plot by adding multiple geom functions to</h4>
</div>
<div id="ggplot-1" class="section level4">
<h4>ggplot</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy)) + geom_smooth(mapping = aes(x = displ, y = hwy))</p>
</div>
<div id="avoiding-duplication-of-variables-by-passing-a-set-of-mappings-to-ggplot" class="section level4">
<h4>Avoiding duplication of variables by passing a set of mappings to ggplot()</h4>
<p>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()</p>
</div>
<div id="placing-mappings-in-a-geom-function-ggplot2-treats-them-as-local" class="section level4">
<h4>Placing mappings in a geom function, ggplot2 treats them as local</h4>
</div>
<div id="mappings-for-the-layer.-uses-these-mappings-to-extend-or-overwrite-the" class="section level4">
<h4>mappings for the layer. Uses these mappings to extend or overwrite the</h4>
</div>
<div id="global-mappings-for-that-layer-only.-this-makes-it-possible-to-display-different" class="section level4">
<h4>global mappings for that layer only. This makes it possible to display different</h4>
</div>
<div id="aesthetics-in-different-layers." class="section level4">
<h4>aesthetics in different layers.</h4>
<p>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth()</p>
</div>
<div id="smooth-line-displays-just-a-subset-of-the-mpg-dataset-the-subcompact-cars." class="section level4">
<h4>smooth line displays just a subset of the mpg dataset, the subcompact cars.</h4>
</div>
<div id="local-data-argument-in-geom_smooth-overrides-the-global-data-argument-in" class="section level4">
<h4>local data argument in geom_smooth() overrides the global data argument in</h4>
</div>
<div id="ggplot-for-that-layer-only." class="section level4">
<h4>ggplot() for that layer only.</h4>
<p>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point(mapping = aes(color = class)) + geom_smooth(data = filter(mpg, class == “subcompact”), se = FALSE)</p>
</div>
<div id="point-plot-with-smooth-line-mapping-separated-by-color" class="section level4">
<h4>Point plot with smooth line mapping separated by color</h4>
<p>ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(se = FALSE)</p>
</div>
<div id="same-graph-by-avoiding-duplication-of-variables-by-passing-in-the-mapping-function" class="section level4">
<h4>Same graph by avoiding duplication of variables by passing in the mapping function</h4>
<p>ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_point() + geom_smooth()</p>
<p>ggplot() + geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))</p>
</div>
<div id="generates-bar-plot-of-the-diamonds-dataset-showing-that-more-diamonds-are" class="section level4">
<h4>generates bar plot of the diamonds dataset showing that more diamonds are</h4>
</div>
<div id="available-with-high-quality-cuts-than-with-low-quality-cuts" class="section level4">
<h4>available with high quality cuts than with low quality cuts</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut))</p>
</div>
<div id="using-geoms-and-stats-interchangeably.-you-can" class="section level4">
<h4>Using geoms and stats interchangeably. You can</h4>
</div>
<div id="recreate-the-previous-plot-using-stat_count-instead-of-geom_bar" class="section level4">
<h4>recreate the previous plot using stat_count() instead of geom_bar()</h4>
<p>ggplot(data = diamonds) + stat_count(mapping = aes(x = cut))</p>
</div>
<div id="overriding-the-default-stat.-change-the-stat-of-geom_bar-from-count" class="section level4">
<h4>Overriding the default stat. change the stat of geom_bar() from count</h4>
</div>
<div id="the-default-to-identity.-lets-one-map-the-height-of-the-bars-to-the-raw" class="section level4">
<h4>(the default) to identity. Lets one map the height of the bars to the raw</h4>
</div>
<div id="values-of-a-y-variable" class="section level4">
<h4>values of a y variable</h4>
<p>demo &lt;- tribble( ~cut, ~freq, “Fair”, 1610, “Good”, 4906, “Very Good”, 12082, “Premium”, 13791, “Ideal”, 21551 )</p>
<p>ggplot(data = demo) + geom_bar(mapping = aes(x = cut, y = freq), stat = “identity”)</p>
</div>
<div id="displaying-a-bar-chart-of-proportion-rather-than-count" class="section level4">
<h4>displaying a bar chart of proportion rather than count</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, y = stat(prop), group = 1))</p>
</div>
<div id="summarises-the-y-values-for-each-unique-x-value-to-draw-attention-to" class="section level4">
<h4>summarises the y values for each unique x value, to draw attention to</h4>
</div>
<div id="the-summary-that-youre-computing" class="section level4">
<h4>the summary that you’re computing</h4>
<p>ggplot(data = diamonds) + stat_summary( mapping = aes(x = cut, y = depth), fun.min = min, fun.max = max, fun = median )</p>
</div>
<div id="creates-proportion-bar-chart-that-is-color-coordinated-where-proportion-is-1" class="section level4">
<h4>creates proportion bar chart that is color coordinated where proportion is = 1</h4>
</div>
<div id="because-proportions-cannot-exceed-100" class="section level4">
<h4>because proportions cannot exceed 100%</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, y = after_stat(prop))) ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = color, y = after_stat(prop)))</p>
</div>
<div id="coloring-bars-using-function-colour-and-fill" class="section level4">
<h4>Coloring bars using function colour and fill</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, colour = cut)) ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = cut))</p>
</div>
<div id="map-the-fill-aesthetic-to-another-variable-like-clarity-the-bars-are" class="section level4">
<h4>map the fill aesthetic to another variable, like clarity: the bars are</h4>
</div>
<div id="automatically-stacked.-each-colored-rectangle-represents-a-combination-of-cut" class="section level4">
<h4>automatically stacked. Each colored rectangle represents a combination of cut</h4>
</div>
<div id="and-clarity" class="section level4">
<h4>and clarity</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity))</p>
</div>
<div id="position-identity-will-place-each-object-exactly-where-it-falls-in-the" class="section level4">
<h4>position = “identity” will place each object exactly where it falls in the</h4>
</div>
<div id="context-of-the-graph.-makes-them-transparent-for-easier-viewing" class="section level4">
<h4>context of the graph. Makes them transparent for easier viewing</h4>
<p>ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + geom_bar(alpha = 1/5, position = “identity”) ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + geom_bar(fill = NA, position = “identity”)</p>
</div>
<div id="position-fill-works-like-stacking-but-makes-each-set-of-stacked-bars-the" class="section level4">
<h4>position = “fill” works like stacking, but makes each set of stacked bars the</h4>
</div>
<div id="same-height." class="section level4">
<h4>same height.</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = “fill”)</p>
</div>
<div id="position-dodge-places-overlapping-objects-directly-beside-one-another." class="section level4">
<h4>position = “dodge” places overlapping objects directly beside one another.</h4>
<p>ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut, fill = clarity), position = “dodge”)</p>
</div>
<div id="position-jitter-adds-a-small-amount-of-random-noise-to-each-point.-this" class="section level4">
<h4>position = “jitter” adds a small amount of random noise to each point. This</h4>
</div>
<div id="spreads-the-points-out-because-no-two-points-are-likely-to-receive-the-same" class="section level4">
<h4>spreads the points out because no two points are likely to receive the same</h4>
</div>
<div id="amount-of-random-noise." class="section level4">
<h4>amount of random noise.</h4>
<p>ggplot(data = mpg) + geom_point(mapping = aes(x = displ, y = hwy), position = “jitter”)</p>
</div>
<div id="point-plot-that-does-not-include-jittering-to-add-random-noise" class="section level4">
<h4>point plot that does not include jittering to add random noise</h4>
<p>ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_point()</p>
</div>
<div id="coord_flip-switches-the-x-and-y-axes.-this-is-useful-for-example" class="section level4">
<h4>coord_flip() switches the x and y axes. This is useful (for example),</h4>
</div>
<div id="if-you-want-horizontal-boxplots" class="section level4">
<h4>if you want horizontal boxplots</h4>
<p>ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot() ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + geom_boxplot() + coord_flip()</p>
</div>
<div id="coord_quickmap-sets-the-aspect-ratio-correctly-for-maps." class="section level4">
<h4>coord_quickmap() sets the aspect ratio correctly for maps.</h4>
<p>nz &lt;- map_data(“nz”)</p>
<p>ggplot(nz, aes(long, lat, group = group)) + geom_polygon(fill = “white”, colour = “black”)</p>
<p>ggplot(nz, aes(long, lat, group = group)) + geom_polygon(fill = “white”, colour = “black”) + coord_quickmap()</p>
</div>
<div id="coord_polar-uses-polar-coordinates.-polar-coordinates-reveal-an-interesting" class="section level4">
<h4>coord_polar() uses polar coordinates. Polar coordinates reveal an interesting</h4>
</div>
<div id="connection-between-a-bar-chart-and-a-coxcomb-chart" class="section level4">
<h4>connection between a bar chart and a Coxcomb chart</h4>
<p>bar &lt;- ggplot(data = diamonds) + geom_bar( mapping = aes(x = cut, fill = cut), show.legend = FALSE, width = 1 ) + theme(aspect.ratio = 1) + labs(x = NULL, y = NULL)</p>
<p>bar + coord_flip() bar + coord_polar()</p>
</div>
<div id="generates-a-regression-line-for-the-plot---shows-that-there-is-not-a-good" class="section level4">
<h4>generates a regression line for the plot - shows that there is not a good</h4>
</div>
<div id="relationship-between-the-two-variables.-creates-a-point-plot-without-randomness" class="section level4">
<h4>relationship between the two variables. Creates a point plot without randomness</h4>
<p>ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + geom_point() + geom_abline() + coord_fixed()</p>
</div>
<div id="adding-add-position-adjustments-stats-coordinate-systems-and-faceting-to-our" class="section level4">
<h4>adding add position adjustments, stats, coordinate systems, and faceting to our</h4>
</div>
<div id="code-template" class="section level4">
<h4>code template:</h4>
<p>#ggplot(data = <DATA>) + #mapping = aes(<MAPPINGS>), #stat = <STAT>, #position = <POSITION> # ) + #<COORDINATE_FUNCTION> + #<FACET_FUNCTION></p>
<p>library(tidyverse)</p>
</div>
<div id="this-line-is-loading-the-package-tidyverse-which-we-already-have-installed" class="section level4">
<h4>this line is loading the package ‘tidyverse’ which we already have installed</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = class)) + geom_smooth(se = FALSE) + labs(title = “Fuel efficiency generally decreases with engine size”)</p>
</div>
<div id="this-section-is-making-a-scatterplot-with-the-function-geom_point-and-then" class="section level4">
<h4>this section is making a scatterplot with the function geom_point and then</h4>
</div>
<div id="making-a-line-of-best-fit-using-the-geom_smooth-function" class="section level4">
<h4>making a line of best fit using the geom_smooth function</h4>
</div>
<div id="this-section-also-employs-the-labs-function-to-make-the-label-for-the-title-of-the-graph" class="section level4">
<h4>this section also employs the labs function to make the label for the title of the graph</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = class)) + geom_smooth(se = FALSE) + labs( title = “Fuel efficiency generally decreases with engine size”, subtitle = “Two seaters (sports cars) are an exception because of their light weight”, caption = “Data from fueleconomy.gov” )</p>
</div>
<div id="only-difference-from-last-section-is-that-it-uses-the-labs-function-to-also-add-a-subtitle-and-caption-to-the-graph" class="section level4">
<h4>Only difference from last section is that it uses the labs function to also add a subtitle and caption to the graph</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + geom_smooth(se = FALSE) + labs( x = “Engine displacement (L)”, y = “Highway fuel economy (mpg)”, colour = “Car type” )</p>
</div>
<div id="difference-is-that-it-uses-x-and-y-to-define-the-axes-labels-and-makes-the-legend-label-car-type" class="section level4">
<h4>Difference is that it uses x and y to define the axes labels and makes the legend label “car type”</h4>
<p>df &lt;- tibble( x = runif(10), y = runif(10) ) ggplot(df, aes(x, y)) + geom_point() + labs( x = quote(sum(x[i] ^ 2, i == 1, n)), y = quote(alpha + beta + frac(delta, theta)) )</p>
</div>
<div id="this-section-is-creating-a-data-frame-using-the-tibble-function" class="section level4">
<h4>this section is creating a data frame using the tibble function</h4>
</div>
<div id="it-also-uses-mathematical-functions-in-place-of-strings-for-the-axes-using-the-quote-function" class="section level4">
<h4>it also uses mathematical functions in place of strings for the axes using the quote function</h4>
<p>best_in_class &lt;- mpg %&gt;% group_by(class) %&gt;% filter(row_number(desc(hwy)) == 1)</p>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + geom_text(aes(label = model), data = best_in_class)</p>
</div>
<div id="pulls-out-the-highest-rated-of-each-class-in-this-case-the-most-efficient-cars" class="section level4">
<h4>pulls out the highest rated of each class, in this case the most efficient cars</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + geom_label(aes(label = model), data = best_in_class, nudge_y = 2, alpha = 0.5)</p>
</div>
<div id="this-section-uses-the-geom_label-function-to-draw-a-rectangle-behind-the-text-with-nudge_y-moving-the-labels-above-the-corresponding-points" class="section level4">
<h4>this section uses the geom_label function to draw a rectangle behind the text, with nudge_y moving the labels above the corresponding points</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + geom_point(size = 3, shape = 1, data = best_in_class) + ggrepel::geom_label_repel(aes(label = model), data = best_in_class)</p>
</div>
<div id="using-the-ggrepel-package-to-automatically-adjust-labels-so-they-dont-overlap" class="section level4">
<h4>Using the ggrepel package to automatically adjust labels so they don’t overlap</h4>
<p>class_avg &lt;- mpg %&gt;% group_by(class) %&gt;% summarise( displ = median(displ), hwy = median(hwy) )</p>
<p>ggplot(mpg, aes(displ, hwy, colour = class)) + ggrepel::geom_label_repel(aes(label = class), data = class_avg, size = 6, label.size = 0, segment.color = NA ) + geom_point() + theme(legend.position = “none”)</p>
</div>
<div id="replacing-the-legend-with-labels-on-the-plot" class="section level4">
<h4>replacing the legend with labels on the plot</h4>
<p>label &lt;- mpg %&gt;% summarise( displ = max(displ), hwy = max(hwy), label = “Increasing engine size is to decreasing fuel economy.” )</p>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point() + geom_text(aes(label = label), data = label, vjust = “top”, hjust = “right”)</p>
</div>
<div id="this-section-adds-a-single-label-to-the-plot-by-creating-a-new-data-frame" class="section level4">
<h4>this section adds a single label to the plot by creating a new data frame</h4>
<p>label &lt;- tibble( displ = Inf, hwy = Inf, label = “Increasing engine size is to decreasing fuel economy.” )</p>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point() + geom_text(aes(label = label), data = label, vjust = “top”, hjust = “right”)</p>
<p>#this section places the text we just created directly on the borders of the plot</p>
<p>“Increasing engine size is related to decreasing fuel economy.” %&gt;% stringr::str_wrap(width = 40) %&gt;% writeLines() “Increasing engine size is related to decreasing fuel economy.”</p>
</div>
<div id="this-section-adds-line-breaks-given-the-number-of-characters" class="section level4">
<h4>this section adds line breaks given the number of characters</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + scale_x_continuous() + scale_y_continuous() + scale_colour_discrete()</p>
</div>
<div id="this-section-chooses-scales-that-are-not-the-default" class="section level4">
<h4>this section chooses scales that are not the default</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point() + scale_y_continuous(breaks = seq(15, 40, by = 5))</p>
</div>
<div id="this-section-uses-the-break-function-to-override-the-default-choice-of-axes-ticks" class="section level4">
<h4>this section uses the break function to override the default choice of axes ticks</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point() + scale_x_continuous(labels = NULL) + scale_y_continuous(labels = NULL)</p>
</div>
<div id="this-section-uses-labels-null-to-get-rid-of-the-numeric-tick-labels-on-the-axes" class="section level4">
<h4>this section uses labels = NULL to get rid of the numeric tick labels on the axes</h4>
<p>presidential %&gt;% mutate(id = 33 + row_number()) %&gt;% ggplot(aes(start, id)) + geom_point() + geom_segment(aes(xend = end, yend = id)) + scale_x_date(NULL, breaks = presidential$start, date_labels = “’%y”)</p>
</div>
<div id="this-section-uses-the-breaks-function-to-highlight-the-observations-in-the-data-set" class="section level4">
<h4>this section uses the breaks function to highlight the observations in the data set</h4>
<p>base &lt;- ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class))</p>
<p>base + theme(legend.position = “left”) base + theme(legend.position = “top”) base + theme(legend.position = “bottom”) base + theme(legend.position = “right”) # the default</p>
</div>
<div id="controlling-where-the-legend-is-drawn" class="section level4">
<h4>controlling where the legend is drawn</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(colour = class)) + geom_smooth(se = FALSE) + theme(legend.position = “bottom”) + guides(colour = guide_legend(nrow = 1, override.aes = list(size = 4)))</p>
<p>#<code>geom_smooth()</code> using method = ‘loess’ and formula ‘y ~ x’</p>
</div>
<div id="uses-nrow-to-control-the-number-of-rows-and-overrides-the-aesthetic-using-override.aes" class="section level4">
<h4>uses nrow to control the number of rows and overrides the aesthetic using override.aes</h4>
<p>ggplot(diamonds, aes(carat, price)) + geom_bin2d()</p>
<p>ggplot(diamonds, aes(log10(carat), log10(price))) + geom_bin2d()</p>
</div>
<div id="log-transforms-the-data-to-make-it-easier-to-see-the-precise-relationship" class="section level4">
<h4>log transforms the data to make it easier to see the precise relationship</h4>
<p>ggplot(diamonds, aes(carat, price)) + geom_bin2d() + scale_x_log10() + scale_y_log10()</p>
</div>
<div id="we-use-this-to-get-rid-of-the-log-axes-labels-and-rescale-the-axes" class="section level4">
<h4>we use this to get rid of the log axes labels and rescale the axes</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = drv))</p>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = drv)) + scale_colour_brewer(palette = “Set1”)</p>
</div>
<div id="adjusts-the-colors-of-the-graph-using-the-palette-function" class="section level4">
<h4>adjusts the colors of the graph using the palette function</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = drv, shape = drv)) + scale_colour_brewer(palette = “Set1”)</p>
</div>
<div id="adds-a-shape-mapping-using-the-shape-function" class="section level4">
<h4>adds a shape mapping using the shape function</h4>
<p>presidential %&gt;% mutate(id = 33 + row_number()) %&gt;% ggplot(aes(start, id, colour = party)) + geom_point() + geom_segment(aes(xend = end, yend = id)) + scale_colour_manual(values = c(Republican = “red”, Democratic = “blue”))</p>
</div>
<div id="this-section-sets-the-colors-of-the-data-set-to-match-the-standard-mapping-of-party-with-colour-party" class="section level4">
<h4>this section sets the colors of the data set to match the standard mapping of party with colour = party</h4>
<p>df &lt;- tibble( x = rnorm(10000), y = rnorm(10000) ) ggplot(df, aes(x, y)) + geom_hex() + coord_fixed()</p>
<p>ggplot(df, aes(x, y)) + geom_hex() + viridis::scale_fill_viridis() + coord_fixed()</p>
</div>
<div id="employs-a-colour-scheme-that-uses-continous-colors" class="section level4">
<h4>employs a colour scheme that uses continous colors</h4>
<p>ggplot(mpg, mapping = aes(displ, hwy)) + geom_point(aes(color = class)) + geom_smooth() + coord_cartesian(xlim = c(5, 7), ylim = c(10, 30))</p>
<p>mpg %&gt;% filter(displ &gt;= 5, displ &lt;= 7, hwy &gt;= 10, hwy &lt;= 30) %&gt;% ggplot(aes(displ, hwy)) + geom_point(aes(color = class)) + geom_smooth()</p>
</div>
<div id="this-section-uses-coord_cartesian-to-zoom-in-on-a-specific-region-of-the-plot" class="section level4">
<h4>this section uses coord_cartesian to zoom in on a specific region of the plot</h4>
<p>suv &lt;- mpg %&gt;% filter(class == “suv”) compact &lt;- mpg %&gt;% filter(class == “compact”)</p>
<p>ggplot(suv, aes(displ, hwy, colour = drv)) + geom_point()</p>
<p>ggplot(compact, aes(displ, hwy, colour = drv)) + geom_point()</p>
</div>
<div id="this-section-subsets-the-data" class="section level4">
<h4>this section subsets the data</h4>
<p>x_scale &lt;- scale_x_continuous(limits = range(mpg<span class="math inline">\(displ)) y_scale &lt;- scale_y_continuous(limits = range(mpg\)</span>hwy)) col_scale &lt;- scale_colour_discrete(limits = unique(mpg$drv))</p>
<p>ggplot(suv, aes(displ, hwy, colour = drv)) + geom_point() + x_scale + y_scale + col_scale</p>
<p>ggplot(compact, aes(displ, hwy, colour = drv)) + geom_point() + x_scale + y_scale + col_scale</p>
</div>
<div id="shares-the-scales-of-the-plots-across-different-plots-using-the-limits-function" class="section level4">
<h4>shares the scales of the plots across different plots using the limits function</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = class)) + geom_smooth(se = FALSE) + theme_bw()</p>
</div>
<div id="uses-theme_bw-to-change-the-theme-of-the-blot" class="section level4">
<h4>uses theme_bw to change the theme of the blot</h4>
<p>ggplot(mpg, aes(displ, hwy)) + geom_point()</p>
</div>
<div id="creates-a-ggplot-as-we-have-been-doing" class="section level4">
<h4>creates a ggplot as we have been doing</h4>
<p>ggsave(“my-plot.pdf”)</p>
<p>#Saving 7 x 4.33 in image #### uses the ggsave function to save our current plot as an image</p>
</div>
</div>
<div id="crim250-final-project---crime-distributions-at-ivy-league-institutions" class="section level1">
<h1>Crim250 Final Project - Crime Distributions at Ivy League Institutions</h1>
<p>Loading Data: Columbia, Yale, UPenn</p>
<pre class="r"><code>dat.Columbia &lt;- read.csv(&#39;jacobdkaplan.com_school_count_Columbia University in the City of New York.csv&#39;)
dat.Upenn &lt;- read.csv(&#39;upenndata.csv&#39;)
dat.Yale &lt;- read.csv(&#39;jacobdkaplan.com_school_count_Yale University.csv&#39;)</code></pre>
</div>
<div id="introduction" class="section level1">
<h1>1. INTRODUCTION</h1>
<p>At the University level, it is important that crime trends are observed in relation to the external factors that may have an effect. Ivy League universities, being private institutions that receive billions of dollars in endowments, should have ample measures in place to control crime rates on campus to maintain the safety of students. In this report, we will observe the total crime trends between the University of Pennsylvania, Yale University, and Columbia University and then take a more specific look at sexual offense trends. These trends will be compared with external research that analyzes police funding and the implementation of Title IX. Ultimately, it is important that more causal research is conducted in this area to observe whether it is beneficial to have privately funded university police departments and whether to bolster Title IX power. The data used in this report contain the total crime data from 2001-2017 for the three Ivy League institutions mentioned above.</p>
</div>
<div id="exploratory-data-analysis" class="section level1">
<h1>2. EXPLORATORY DATA ANALYSIS</h1>
<div id="data-description" class="section level4">
<h4>2.1 Data Description</h4>
<p>The selected dataset was compiled data from Jacob Kaplan on total crimes reported at Universities.1 All of the data comes from the Department of Education Office of Postsecondary Education, which collects crime data from colleges. The following variables were the focus of the analysis: total number of aggravated assault, total number of arson, total number of motor vehicle theft, total number of non-negligent manslaughter, total number of negligent manslaughter, total number of sex offenses. The variables total number of on campus sex crimes and total number of off campus sex crimes were explored as well. All datasets used for this analysis individually contain 17 years of data with 1039 observations.</p>
<pre class="r"><code>dim(dat.Columbia)</code></pre>
<pre><code>## [1]   17 1039</code></pre>
<pre class="r"><code>dim(dat.Yale)</code></pre>
<pre><code>## [1]   17 1039</code></pre>
<pre class="r"><code>dim(dat.Upenn)</code></pre>
<pre><code>## [1]   17 1039</code></pre>
</div>
<div id="missing-values" class="section level4">
<h4>2.2 MISSING VALUES</h4>
<p>There are many missing values because, different from the value of 0, there are crime “categories” that do not have any reported crime data for certain years. For example, looking at the University of Pennsylvania data, there is no data for off-campus rape crimes until 2014. This will affect our data analysis, because the crime statistics may seem lower than they actually are.</p>
</div>
<div id="university-locations" class="section level4">
<h4>2.3 UNIVERSITY LOCATIONS</h4>
<p>The three universities are located in urban settings. University of Pennsylvania is located in Philadelphia, PA (2019 pop. = 1.58 million).2 Columbia University is located in New York City, NY (2019 pop. = 8.33 million).2 Yale University is in New Haven, CT (2019 pop. = 130,250).2 All population data was retrieved from the US census population estimates.</p>
</div>
<div id="campus-police-force" class="section level4">
<h4>2.4 CAMPUS POLICE FORCE</h4>
<pre><code>The University of Pennsylvania’s Division of Public Safety (DPS) comprises 180 personnel and 121 of these are sworn-in University of Pennsylvania police officers.3 The Yale Police Department (YPD) comprises 93 sworn-in police officers.4 Due to New York regulations, Columbia University has 147 full-time security officers and no sworn-in officers.5  These security officers cannot carry firearms or arrest individuals, but they can detain suspected criminals on the University property. However, Columbia University is in the 26th precinct of the NYPD.6 </code></pre>
</div>
<div id="total-crimes-per-year" class="section level4">
<h4>2.5 TOTAL CRIMES PER YEAR</h4>
<pre class="r"><code>plot(dat.Columbia$year, dat.Columbia$crimes_total_total, type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Crimes at Columbia from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of offenses reported to police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-27-1.png" width="672" /></p>
<pre class="r"><code>plot(dat.Yale$year, dat.Yale$crimes_total_total, type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Crimes at Yale from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of offenses reported to police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-27-2.png" width="672" /></p>
<pre class="r"><code>plot(dat.Upenn$year, dat.Upenn$crimes_total_total, type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Crimes at UPenn from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of offenses reported to police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-27-3.png" width="672" /></p>
</div>
<div id="average-of-total-sex-offenses-per-year" class="section level4">
<h4>2.6 AVERAGE OF TOTAL SEX OFFENSES PER YEAR</h4>
<pre class="r"><code>plot(dat.Columbia$year, dat.Columbia$crimes_total_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Sex Crimes at Columbia from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-28-1.png" width="672" /></p>
<pre class="r"><code>plot(dat.Yale$year, dat.Yale$crimes_total_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Sex Crimes at Yale from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-28-2.png" width="672" /></p>
<pre class="r"><code>plot(dat.Upenn$year, dat.Upenn$crimes_total_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Total Number of Reported Sex Crimes at Upenn from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-28-3.png" width="672" /></p>
</div>
<div id="differences-by-onoff-campus" class="section level4">
<h4>2.7 DIFFERENCES BY ON/OFF CAMPUS</h4>
</div>
<div id="on-campus-sex-offenses" class="section level4">
<h4>2.7.1 ON CAMPUS SEX OFFENSES</h4>
<pre class="r"><code>plot(dat.Columbia$year, dat.Columbia$crimes_on_campus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of On Campus Total Number of Reported Sex Crimes at Columbia from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-29-1.png" width="672" /></p>
<pre class="r"><code>plot(dat.Yale$year, dat.Yale$crimes_on_campus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of On Campus Total Number of Reported Sex Crimes at Yale from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-29-2.png" width="672" /></p>
<pre class="r"><code>plot(dat.Upenn$year, dat.Upenn$crimes_on_campus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of On Campus Total Number of Reported Sex Crimes at UPenn from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-29-3.png" width="672" /></p>
<p>2.7.2 OFF CAMPUS SEX OFFENSES</p>
<pre class="r"><code>plot(dat.Columbia$year, dat.Columbia$crimes_noncampus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Off Campus Total Number of Reported Sex Crimes at Columbia from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-30-1.png" width="672" /></p>
<pre class="r"><code>plot(dat.Yale$year, dat.Yale$crimes_noncampus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Off Campus Total Number of Reported Sex Crimes at Yale from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-30-2.png" width="672" /></p>
<pre class="r"><code>plot(dat.Upenn$year, dat.Upenn$crimes_noncampus_sex_offenses_total,  type = &quot;b&quot;, main = &quot;Scatterplot of Off Campus Total Number of Reported Sex Crimes at Upenn from 2001-2017&quot;,
     xlab = &quot;Year&quot;, ylab = &quot;Number of Offenses Reported to Police&quot;, cex.axis = 0.75)

axis(1, at=seq(2001,2017,1), cex.axis=0.75)</code></pre>
<p><img src="Assignments_files/figure-html/unnamed-chunk-30-3.png" width="672" /></p>
</div>
<div id="differences-in-different-crime-types" class="section level4">
<h4>2.8 DIFFERENCES IN DIFFERENT CRIME TYPES</h4>
<div class="figure">
<img src="~/Desktop/testGitHub/SaraWhitR/ColumbiaBarGraph.png" alt="" />
<p class="caption">Differences In Different Crime Types</p>
</div>
<div class="figure">
<img src="UpennBarGraph.png" alt="" />
<p class="caption">Differences In Different Crime Types</p>
</div>
<p><img src="YaleBarGraph.png" alt="Differences In Different Crime Types" /> # CAUSAL ANALYSIS</p>
</div>
<div id="causal-parameter-of-interest" class="section level4">
<h4>3.1 CAUSAL PARAMETER OF INTEREST</h4>
<pre><code>The causal parameters of interest are the size and funding of the police forces of the three Ivy League institutions: University of Pennsylvania, Yale University, and Columbia University. Additionally, we note the effect of Title IX guidelines on the sexual offense trends. While Columbia has 147 security officers rather than a private police force, Columbia benefits from the NYPD as they are located in the 26th precinct. Due to the size and power of the NYPD, Columbia’s total crime trend could be more reflective of the crime trends in the surrounding New York area. UPenn has a private police force of 121 sworn officers, which receives 27 million dollars of funding. UPenn’s negative crime trend could be a result of the robust size and funding of the police force, but without causal analysis and true experiments that include randomization, it is unclear whether this external factor has a relevant impact. Finally, on-campus sexual offense trends could be influenced by the causal parameter of Title IX guidelines and their implementation in university proceedings surrounding sexual offense cases. Title IX allows increased protections and assurance of investigation for on-campus students, which could possibly explain the high reporting rates for sexual offenses. Conversely, Title IX guidelines limit protections in off campus offenses noted in our discussion section.7 
It is important to note that these causal parameters can only be hypothesized as we do not have sufficient data to analyze whether they play an influential role in our EDA of the crime distributions of the three Ivy Leagues explored. </code></pre>
</div>
<div id="proposed-causal-dag" class="section level4">
<h4>3.2 PROPOSED CAUSAL DAG</h4>
<p>The proposed causal DAG consists of two actions, the outcomes of the actions, and the confounding variables that may impact both the actions and the outcomes. In our case of understanding the crime distribution of the Columbia, Yale, and UPenn, the actions that influence the crime reporting rates are the strength and presence of the campus funded police force and Title IX when regarding the reporting of sex offenses. The expected outcomes of higher funding and strong on campus police force would seemingly decrease total crime rates whereas decreased funding and smaller police force would result in higher crime. Title IX’s on-campus guidelines would result in higher crime reporting of sex offenses due to increased victim protection whereas their off campus guidelines would result in decreased reporting. However, the confounding variables that may impact both these actions and outcomes are reporting bias, in that there may be failure to report by police offices as well as failure to report by victim (sex assault), and the danger of the location of the school.</p>
<div class="figure">
<img src="CausalDAG.png" alt="" />
<p class="caption">Causal DAG</p>
</div>
</div>
</div>
<div id="discussion" class="section level1">
<h1>4. DISCUSSION</h1>
<p>We wanted to determine whether 1) There was a significant difference in total crime rates and sexual offenses between three different urban, Ivy League institutions, and 2) if police size and funding, and Title IX guidelines influenced this relationship. Due to a lack of sufficient data on which we could perform linear regression to explore the correlation between these two actions (police funding and Title IX guidelines), it is unclear whether they have an impact on the total crime trends and sexual offense rates at any of the Ivy Leagues we analyzed. However, overall, we found that the University of Pennsylvania had the highest total number of reported crimes from 2001-2017, with a total of 2069 crimes compared to Yale (1991) and Columbia (1589). It is important to note that Columbia had two years of missing data, which could change how its crime rates actually compare to the other universities. Yale University had the highest number of reported sex offenses (246) compared to Columbia University (196) and University of Pennsylvania (216). We find this especially interesting because UPenn has the highest crime rate, despite having the largest number of on-campus sworn-in officers. Additionally, it is intriguing that Yale University is located in the smallest city (population =130,250) of the three schools analyzed, but still has the highest number of reported sex offenses. Yale University also has the lowest police force funding ($10 million), despite having the largest endowment ($42.3 billion) of the three Ivies.2,8,9 We also found that almost all sex offenses reported to the respective campus police forces occurred on campus, rather than off campus. It is possible that this is because off-campus sex offenses are reported to the city police forces. In terms of Title IX providing explanation for the stark difference between on campus and off campus sexual offense trends, new Title IX guidelines do not require universities to investigate events that occur off campus. Therefore, there could ultimately be higher off campus sexual offense trends due to lack of investigation by universities. Our results have some limitations. The Columbia University data set was missing crime data for 2002 and 2004. The data sets that we used were subject to reporting bias and missing data. Failure to report by police officers and failure to report by victim, which is especially prevalent with sexual assault cases, has an effect on the total number of crimes reported, as well as the total number of sexual offenses reported. In addition, due to limited data, we only used scatter and box plots to compare the crime distribution and analyze the relationship between police force funding, Title IX enactment, and crime distribution. The use of linear regression would allow for strong analysis between these variables.</p>
</div>
<div id="appendix" class="section level1">
<h1>5. Appendix</h1>
<p><img src="UpennAppendix.png" alt="Appendix 1" /> <img src="ColumbiaAppendix.png" alt="Appendix 2" /></p>
<div class="figure">
<img src="YaleAppendix.png" alt="" />
<p class="caption">Appendix 3</p>
</div>
</div>
<div id="sources" class="section level1">
<h1>6 Sources</h1>
<p>Kaplan, J. (n.d.). Crimes On University Campuses. Data | Jacob Kaplan. Retrieved December 7, 2021, from <a href="https://jacobdkaplan.com/data.html" class="uri">https://jacobdkaplan.com/data.html</a>. Bureau, U. S. C. (2021, October 8). American Community survey 5-year data (2009-2019). Census.gov. Retrieved December 7, 2021, from <a href="https://www.census.gov/data/developers/data-sets/acs-5year.html" class="uri">https://www.census.gov/data/developers/data-sets/acs-5year.html</a>. Pennsylvania, U. of. (n.d.). About our division. Division of Public Safety. Retrieved December 7, 2021, from <a href="https://www.publicsafety.upenn.edu/about/" class="uri">https://www.publicsafety.upenn.edu/about/</a>. Yale University. (2020, June). Yale Police Department. It’s Your Yale. Retrieved December 7, 2021, from <a href="https://your.yale.edu/community/public-safety/yale-police-department" class="uri">https://your.yale.edu/community/public-safety/yale-police-department</a>. Heinzerling, K. (2017, October 8). With 120 officers, Penn has the largest private police force in Pennsylvania. The Daily Pennsylvanian. Retrieved December 7, 2021, from <a href="https://www.thedp.com/article/2017/10/with-120-officers-penn-has-the-largest-private-police-force-in-pennsylvania" class="uri">https://www.thedp.com/article/2017/10/with-120-officers-penn-has-the-largest-private-police-force-in-pennsylvania</a>. 26th precinct. 26 Precinct - NYPD. (n.d.). Retrieved December 7, 2021, from <a href="https://www1.nyc.gov/site/nypd/bureaus/patrol/precincts/26th-precinct.page" class="uri">https://www1.nyc.gov/site/nypd/bureaus/patrol/precincts/26th-precinct.page</a>. Feldman, S. (2018, October 8). Yale and Title IX: A Complicated History and an Unclear Future. The Politic. Retrieved December 7, 2021, from <a href="https://thepolitic.org/yale-and-title-ix-a-complicated-history-and-an-unclear-future/" class="uri">https://thepolitic.org/yale-and-title-ix-a-complicated-history-and-an-unclear-future/</a>.<br />
Why: Black students for disarmament at Yale. bsdy. (n.d.). Retrieved December 7, 2021, from <a href="https://www.defundypd.com/why" class="uri">https://www.defundypd.com/why</a>. Yale Investments Office. (n.d.). Retrieved December 07, 2021, from <a href="https://investments.yale.edu/" class="uri">https://investments.yale.edu/</a></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
